name: Tox Testing Suite

on:
  - push
  - pull_request

jobs:
  test-tox:
    outputs:
      dir: ${{ steps.pip-cache.outputs.dir }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
        exclude:
          - platform: windows-latest
            python-version: pypy3

    steps:
      - uses: actions/checkout@v1

      - name: Tox cache
        uses: actions/cache@v2
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ hashFiles('**/tox.ini') }}
          restore-keys: ${{ runner.os }}-tox-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/tox.ini') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install tox tox-gh-actions

      - name: Test with tox
        run: tox
        env:
          PLATFORM: ${{ matrix.platform }}

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-data
          path: .coverage/

  coverage:
    needs: test-tox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ${{ needs.test-tox.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/tox.ini') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install tox tox-gh-actions

      - uses: actions/download-artifact@v2
        with:
          name: coverage-data
          path: .coverage/

      - name: Coverage
        run: tox -e report

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            .coverage/coverage.xml:coverage.py
